# Generated by Django 5.2.3 on 2025-07-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quizresult_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('question_number', models.IntegerField()),
                ('correct_keywords', models.JSONField()),
                ('user_answer', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
